[env]
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    https://github.com/LSatan/SmartRC-CC1101-Driver-Lib.git
    gyverlibs/GyverButton
    sui77/rc-switch

[env:esp32dev]
platform = espressif32
board = esp32dev
build_flags = -D BOARD_ESP32_DEV

[env:esp32c3_supermini]
platform = espressif32
board = esp32-c3-devkitm-1
build_flags = 
    -D BOARD_ESP32_C3_SUPERMINI
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp-hack]
platform = espressif32
board = esp32dev
build_flags = 
    -D BOARD_ESP_HACK
    -D USE_SH1106
lib_deps = 
    ${env.lib_deps}
    adafruit/Adafruit SH110X


